#项目端口

spring:
  #thymeleaf模板配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

    #静态资源路径
  mvc:
    static-path-pattern: /static/**
      #关掉原生icon图标
#    favicon:
#      enabled: false

    #content-type: text/html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itmp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 197442
  application:
    name: springboot-webAdmin
    jpa:
      show-sql: true
      database: mysql
      #generate-ddl: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        naming:
          #解决使用其他库的表时候，把小数点变成下划线，导致sql无法成功执行。
          #这是由于物理命名策略引起的，大写字母变小写，加_下划线（hibernate5以上高版本）
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #ddl-auto: update
      #ddl-auto: update
#    datasource:
#      url: jdbc:mysql://rm-bp1k374xl0x6v67pago.mysql.rds.aliyuncs.com:3306/school?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#      username: root
#      password: Yp001001
#      driver-class-name: com.mysql.jdbc.Driver
#      type: com.zaxxer.hikari.HikariDataSource
#      hikari:
#        auto-commit: true
#        minimum-idle: 2
#        idle-timeout: 60000
#        connection-timeout: 30000
#        max-lifetime: 1800000
#        pool-name: DatebookHikariCP
    #thymeleaf模板配置
    thymeleaf:
      cache: false
      enabled: true
      prefix: classpath:/static/layuimini/
      suffix: .html
      #严格执行H5标准
      mode: LEGACYHTML5
      encoding: UTF-8
      servlet:
        content-type: text/html

#    resources:
#      chain:
#        strategy:
#          content:
#            enabled: true
#            paths: /**




# swagger
swagger:
  enable: true

#本地开发环境配置中心


  #连接超时，单位为毫秒，-1永不超时
#  connection-timeout: 60000
  #设置tomcat参数
  tomcat:
    uri-encoding: utf-8
    max-connections: 10000
    min-spare-threads: 10
    #最大220个并发，可以达到不丢包（可以自己实测），默认为200。
    max-threads: 220
    #配置访问路径，默认为/
    #servlet:
#    context-path: /index/main



#配置日志文件参数
logging:
  file:
    path: ./adminLog.log
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
    hibernate: debug

itmp:
  debug: true
  global-prevent-duplicate: true

# 配置mybatis映射文件的扫描信息
mybatis-plus:
  mapper-locations: classpath*:com/huadi/itmp/modules/*/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

